import 'dart:core';

import 'package:flutter/material.dart';

class DataHelper {
  static Map<String, List<Map<String, dynamic>>> CategoryLabel = {
    'MOFASAL': [
      {"souraName": "Adh-Dhaariyat", "souraNb": 51},
      {"souraName": "At-Tur", "souraNb": 52},
      {"souraName": "An-Najm", "souraNb": 53},
      {"souraName": "Al-Qamar", "souraNb": 54},
      {"souraName": "Ar-Rahmaan", "souraNb": 55},
      {"souraName": "Al-Waaqia", "souraNb": 56},
      {"souraName": "Al-Hadid", "souraNb": 57},
      {"souraName": "Al-Mujaadila", "souraNb": 58},
      {"souraName": "Al-Hashr", "souraNb": 59},
      {"souraName": "Al-Mumtahana", "souraNb": 60},
      {"souraName": "As-Saff", "souraNb": 61},
      {"souraName": "Al-Jumu'a", "souraNb": 62},
      {"souraName": "Al-Munaafiqoon", "souraNb": 63},
      {"souraName": "At-Taghaabun", "souraNb": 64},
      {"souraName": "At-Talaaq", "souraNb": 65},
      {"souraName": "At-Tahrim", "souraNb": 66},
      {"souraName": "Al-Mulk", "souraNb": 67},
      {"souraName": "Al-Qalam", "souraNb": 68},
      {"souraName": "Al-Haaqqa", "souraNb": 69},
      {"souraName": "Al-Ma'aarij", "souraNb": 70},
      {"souraName": "Nooh", "souraNb": 71},
      {"souraName": "Al-Jinn", "souraNb": 72},
      {"souraName": "Al-Muzzammil", "souraNb": 73},
      {"souraName": "Al-Muddaththir", "souraNb": 74},
      {"souraName": "Al-Qiyaama", "souraNb": 75},
      {"souraName": "Al-Insaan", "souraNb": 76},
      {"souraName": "Al-Mursalaat", "souraNb": 77},
      {"souraName": "An-Naba", "souraNb": 78},
      {"souraName": "An-Naazi'aat", "souraNb": 79},
      {"souraName": "Abasa", "souraNb": 80},
      {"souraName": "At-Takwir", "souraNb": 81},
      {"souraName": "Al-Infitaar", "souraNb": 82},
      {"souraName": "Al-Mutaffifin", "souraNb": 83},
      {"souraName": "Al-Inshiqaaq", "souraNb": 84},
      {"souraName": "Al-Burooj", "souraNb": 85},
      {"souraName": "At-Taariq", "souraNb": 86},
      {"souraName": "Al-A'laa", "souraNb": 87},
      {"souraName": "Al-Ghaashiya", "souraNb": 88},
      {"souraName": "Al-Fajr", "souraNb": 89},
      {"souraName": "Al-Balad", "souraNb": 90},
      {"souraName": "Ash-Shams", "souraNb": 91},
      {"souraName": "Al-Lail", "souraNb": 92},
      {"souraName": "Ad-Dhuhaa", "souraNb": 93},
      {"souraName": "Ash-Sharh", "souraNb": 94},
      {"souraName": "At-Tin", "souraNb": 95},
      {"souraName": "Al-Alaq", "souraNb": 96},
      {"souraName": "Al-Qadr", "souraNb": 97},
      {"souraName": "Al-Bayyina", "souraNb": 98},
      {"souraName": "Az-Zalzala", "souraNb": 99},
      {"souraName": "Al-Aadiyaat", "souraNb": 100},
      {"souraName": "Al-Qaari'a", "souraNb": 101},
      {"souraName": "At-Takaathur", "souraNb": 102},
      {"souraName": "Al-Asr", "souraNb": 103},
      {"souraName": "Al-Humaza", "souraNb": 104},
      {"souraName": "Al-Fil", "souraNb": 105},
      {"souraName": "Quraish", "souraNb": 106},
      {"souraName": "Al-Maa'un", "souraNb": 107},
      {"souraName": "Al-Kawthar", "souraNb": 108},
      {"souraName": "Al-Kaafiroon", "souraNb": 109},
      {"souraName": "An-Nasr", "souraNb": 110},
      {"souraName": "Al-Masad", "souraNb": 111},
      {"souraName": "Al-Ikhlaas", "souraNb": 112},
      {"souraName": "Al-Falaq", "souraNb": 113},
      {"souraName": "An-Naas", "souraNb": 114}
    ],
    'MATHANI': [
      {"souraName": "Maryam", "souraNb": 19},
      {"souraName": "Taa-Haa", "souraNb": 20},
      {"souraName": "Al-Anbiyaa", "souraNb": 21},
      {"souraName": "Al-Hajj", "souraNb": 22},
      {"souraName": "Al-Muminoon", "souraNb": 23},
      {"souraName": "An-Noor", "souraNb": 24},
      {"souraName": "Al-Furqaan", "souraNb": 25},
      {"souraName": "Ash-Shu'araa", "souraNb": 26},
      {"souraName": "An-Naml", "souraNb": 27},
      {"souraName": "Al-Qasas", "souraNb": 28},
      {"souraName": "Al-Ankaboot", "souraNb": 29},
      {"souraName": "Ar-Room", "souraNb": 30},
      {"souraName": "Luqman", "souraNb": 31},
      {"souraName": "As-Sajda", "souraNb": 32},
      {"souraName": "Al-Ahzaab", "souraNb": 33},
      {"souraName": "Saba", "souraNb": 34},
      {"souraName": "Faatir", "souraNb": 35},
      {"souraName": "Yaseen", "souraNb": 36},
      {"souraName": "As-Saaffaat", "souraNb": 37},
      {"souraName": "Saad", "souraNb": 38},
      {"souraName": "Az-Zumar", "souraNb": 39},
      {"souraName": "Ghafir", "souraNb": 40},
      {"souraName": "Fussilat", "souraNb": 41},
      {"souraName": "Ash-Shura", "souraNb": 42},
      {"souraName": "Az-Zukhruf", "souraNb": 43},
      {"souraName": "Ad-Dukhaan", "souraNb": 44},
      {"souraName": "Al-Jaathiya", "souraNb": 45},
      {"souraName": "Al-Ahqaf", "souraNb": 46},
      {"souraName": "Muhammad", "souraNb": 47},
      {"souraName": "Al-Fath", "souraNb": 48},
      {"souraName": "Al-Hujuraat", "souraNb": 49},
      {"souraName": "Qaaf", "souraNb": 50}
    ],
    'MIIN': [
      {"souraName": "Al-Anfaal", "souraNb": 8},
      {"souraName": "At-Tawba", "souraNb": 9},
      {"souraName": "Yunus", "souraNb": 10},
      {"souraName": "Hud", "souraNb": 11},
      {"souraName": "Yusuf", "souraNb": 12},
      {"souraName": "Ar-Ra'd", "souraNb": 13},
      {"souraName": "Ibrahim", "souraNb": 14},
      {"souraName": "Al-Hijr", "souraNb": 15},
      {"souraName": "An-Nahl", "souraNb": 16},
      {"souraName": "Al-Israa", "souraNb": 17},
      {"souraName": "Al-Kahf", "souraNb": 18}
    ],
    'TIWAL': [
      {"souraName": "Al-Faatiha", "souraNb": 1},
      {"souraName": "Al-Baqara", "souraNb": 2},
      {"souraName": "Aal-i-Imraan", "souraNb": 3},
      {"souraName": "An-Nisaa", "souraNb": 4},
      {"souraName": "Al-Maaida", "souraNb": 5},
      {"souraName": "Al-An'aam", "souraNb": 6},
      {"souraName": "Al-A'raaf", "souraNb": 7}
    ]
  };

  static String appTitle = 'asas liismaiil';
  static double minimumPadding = 5;
  static List<Map<String, dynamic>> mofasal = [
    {"souraName": "Adh-Dhaariyat", "souraNb": 51},
    {"souraName": "At-Tur", "souraNb": 52},
    {"souraName": "An-Najm", "souraNb": 53},
    {"souraName": "Al-Qamar", "souraNb": 54},
    {"souraName": "Ar-Rahmaan", "souraNb": 55},
    {"souraName": "Al-Waaqia", "souraNb": 56},
    {"souraName": "Al-Hadid", "souraNb": 57},
    {"souraName": "Al-Mujaadila", "souraNb": 58},
    {"souraName": "Al-Hashr", "souraNb": 59},
    {"souraName": "Al-Mumtahana", "souraNb": 60},
    {"souraName": "As-Saff", "souraNb": 61},
    {"souraName": "Al-Jumu'a", "souraNb": 62},
    {"souraName": "Al-Munaafiqoon", "souraNb": 63},
    {"souraName": "At-Taghaabun", "souraNb": 64},
    {"souraName": "At-Talaaq", "souraNb": 65},
    {"souraName": "At-Tahrim", "souraNb": 66},
    {"souraName": "Al-Mulk", "souraNb": 67},
    {"souraName": "Al-Qalam", "souraNb": 68},
    {"souraName": "Al-Haaqqa", "souraNb": 69},
    {"souraName": "Al-Ma'aarij", "souraNb": 70},
    {"souraName": "Nooh", "souraNb": 71},
    {"souraName": "Al-Jinn", "souraNb": 72},
    {"souraName": "Al-Muzzammil", "souraNb": 73},
    {"souraName": "Al-Muddaththir", "souraNb": 74},
    {"souraName": "Al-Qiyaama", "souraNb": 75},
    {"souraName": "Al-Insaan", "souraNb": 76},
    {"souraName": "Al-Mursalaat", "souraNb": 77},
    {"souraName": "An-Naba", "souraNb": 78},
    {"souraName": "An-Naazi'aat", "souraNb": 79},
    {"souraName": "Abasa", "souraNb": 80},
    {"souraName": "At-Takwir", "souraNb": 81},
    {"souraName": "Al-Infitaar", "souraNb": 82},
    {"souraName": "Al-Mutaffifin", "souraNb": 83},
    {"souraName": "Al-Inshiqaaq", "souraNb": 84},
    {"souraName": "Al-Burooj", "souraNb": 85},
    {"souraName": "At-Taariq", "souraNb": 86},
    {"souraName": "Al-A'laa", "souraNb": 87},
    {"souraName": "Al-Ghaashiya", "souraNb": 88},
    {"souraName": "Al-Fajr", "souraNb": 89},
    {"souraName": "Al-Balad", "souraNb": 90},
    {"souraName": "Ash-Shams", "souraNb": 91},
    {"souraName": "Al-Lail", "souraNb": 92},
    {"souraName": "Ad-Dhuhaa", "souraNb": 93},
    {"souraName": "Ash-Sharh", "souraNb": 94},
    {"souraName": "At-Tin", "souraNb": 95},
    {"souraName": "Al-Alaq", "souraNb": 96},
    {"souraName": "Al-Qadr", "souraNb": 97},
    {"souraName": "Al-Bayyina", "souraNb": 98},
    {"souraName": "Az-Zalzala", "souraNb": 99},
    {"souraName": "Al-Aadiyaat", "souraNb": 100},
    {"souraName": "Al-Qaari'a", "souraNb": 101},
    {"souraName": "At-Takaathur", "souraNb": 102},
    {"souraName": "Al-Asr", "souraNb": 103},
    {"souraName": "Al-Humaza", "souraNb": 104},
    {"souraName": "Al-Fil", "souraNb": 105},
    {"souraName": "Quraish", "souraNb": 106},
    {"souraName": "Al-Maa'un", "souraNb": 107},
    {"souraName": "Al-Kawthar", "souraNb": 108},
    {"souraName": "Al-Kaafiroon", "souraNb": 109},
    {"souraName": "An-Nasr", "souraNb": 110},
    {"souraName": "Al-Masad", "souraNb": 111},
    {"souraName": "Al-Ikhlaas", "souraNb": 112},
    {"souraName": "Al-Falaq", "souraNb": 113},
    {"souraName": "An-Naas", "souraNb": 114}
  ];
  static List<Map<String, dynamic>> mathani = [
    {"souraName": "Maryam", "souraNb": 19},
    {"souraName": "Taa-Haa", "souraNb": 20},
    {"souraName": "Al-Anbiyaa", "souraNb": 21},
    {"souraName": "Al-Hajj", "souraNb": 22},
    {"souraName": "Al-Muminoon", "souraNb": 23},
    {"souraName": "An-Noor", "souraNb": 24},
    {"souraName": "Al-Furqaan", "souraNb": 25},
    {"souraName": "Ash-Shu'araa", "souraNb": 26},
    {"souraName": "An-Naml", "souraNb": 27},
    {"souraName": "Al-Qasas", "souraNb": 28},
    {"souraName": "Al-Ankaboot", "souraNb": 29},
    {"souraName": "Ar-Room", "souraNb": 30},
    {"souraName": "Luqman", "souraNb": 31},
    {"souraName": "As-Sajda", "souraNb": 32},
    {"souraName": "Al-Ahzaab", "souraNb": 33},
    {"souraName": "Saba", "souraNb": 34},
    {"souraName": "Faatir", "souraNb": 35},
    {"souraName": "Yaseen", "souraNb": 36},
    {"souraName": "As-Saaffaat", "souraNb": 37},
    {"souraName": "Saad", "souraNb": 38},
    {"souraName": "Az-Zumar", "souraNb": 39},
    {"souraName": "Ghafir", "souraNb": 40},
    {"souraName": "Fussilat", "souraNb": 41},
    {"souraName": "Ash-Shura", "souraNb": 42},
    {"souraName": "Az-Zukhruf", "souraNb": 43},
    {"souraName": "Ad-Dukhaan", "souraNb": 44},
    {"souraName": "Al-Jaathiya", "souraNb": 45},
    {"souraName": "Al-Ahqaf", "souraNb": 46},
    {"souraName": "Muhammad", "souraNb": 47},
    {"souraName": "Al-Fath", "souraNb": 48},
    {"souraName": "Al-Hujuraat", "souraNb": 49},
    {"souraName": "Qaaf", "souraNb": 50}
  ];
  static List<Map<String, dynamic>> miin = [
    {"souraName": "Al-Anfaal", "souraNb": 8},
    {"souraName": "At-Tawba", "souraNb": 9},
    {"souraName": "Yunus", "souraNb": 10},
    {"souraName": "Hud", "souraNb": 11},
    {"souraName": "Yusuf", "souraNb": 12},
    {"souraName": "Ar-Ra'd", "souraNb": 13},
    {"souraName": "Ibrahim", "souraNb": 14},
    {"souraName": "Al-Hijr", "souraNb": 15},
    {"souraName": "An-Nahl", "souraNb": 16},
    {"souraName": "Al-Israa", "souraNb": 17},
    {"souraName": "Al-Kahf", "souraNb": 18}
  ];
  static List<Map<String, dynamic>> tiwal = [
    {"souraName": "Al-Faatiha", "souraNb": 1},
    {"souraName": "Al-Baqara", "souraNb": 2},
    {"souraName": "Aal-i-Imraan", "souraNb": 3},
    {"souraName": "An-Nisaa", "souraNb": 4},
    {"souraName": "Al-Maaida", "souraNb": 5},
    {"souraName": "Al-An'aam", "souraNb": 6},
    {"souraName": "Al-A'raaf", "souraNb": 7}
  ];
  static List<String> flags = [
    "ad.png",
    "ae.png",
    "af.png",
    "ag.png",
    "ai.png",
    "al.png",
    "am.png",
    "an.png",
    "ao.png",
    "aq.png",
    "ar.png",
    "as.png",
    "at.png",
    "au.png",
    "aw.png",
    "ax.png",
    "az.png",
    "ba.png",
    "bb.png",
    "bd.png",
    "be.png",
    "bf.png",
    "bg.png",
    "bh.png",
    "bi.png",
    "bj.png",
    "bl.png",
    "bm.png",
    "bn.png",
    "bo.png",
    "bq.png",
    "br.png",
    "bs.png",
    "bt.png",
    "bv.png",
    "bw.png",
    "by.png",
    "bz.png",
    "ca.png",
    "cc.png",
    "cd.png",
    "cf.png",
    "cg.png",
    "ch.png",
    "ci.png",
    "ck.png",
    "cl.png",
    "cm.png",
    "cn.png",
    "co.png",
    "cr.png",
    "cu.png",
    "cv.png",
    "cw.png",
    "cx.png",
    "cy.png",
    "cz.png",
    "de.png",
    "dj.png",
    "dk.png",
    "dm.png",
    "do.png",
    "dz.png",
    "ec.png",
    "ee.png",
    "eg.png",
    "eh.png",
    "er.png",
    "es.png",
    "et.png",
    "eu.png",
    "fi.png",
    "fj.png",
    "fk.png",
    "fm.png",
    "fo.png",
    "fr.png",
    "ga.png",
    "gb-eng.png",
    "gb-nir.png",
    "gb-sct.png",
    "gb-wls.png",
    "gb.png",
    "gd.png",
    "ge.png",
    "gf.png",
    "gg.png",
    "gh.png",
    "gi.png",
    "gl.png",
    "gm.png",
    "gn.png",
    "gp.png",
    "gq.png",
    "gr.png",
    "gs.png",
    "gt.png",
    "gu.png",
    "gw.png",
    "gy.png",
    "hk.png",
    "hm.png",
    "hn.png",
    "hr.png",
    "ht.png",
    "hu.png",
    "id.png",
    "ie.png",
    "il.png",
    "im.png",
    "in.png",
    "io.png",
    "iq.png",
    "ir.png",
    "is.png",
    "it.png",
    "je.png",
    "jm.png",
    "jo.png",
    "jp.png",
    "ke.png",
    "kg.png",
    "kh.png",
    "ki.png",
    "km.png",
    "kn.png",
    "kp.png",
    "kr.png",
    "kw.png",
    "ky.png",
    "kz.png",
    "la.png",
    "lb.png",
    "lc.png",
    "li.png",
    "lk.png",
    "lr.png",
    "ls.png",
    "lt.png",
    "lu.png",
    "lv.png",
    "ly.png",
    "ma.png",
    "mc.png",
    "md.png",
    "me.png",
    "mf.png",
    "mg.png",
    "mh.png",
    "mk.png",
    "ml.png",
    "mm.png",
    "mn.png",
    "mo.png",
    "mp.png",
    "mq.png",
    "mr.png",
    "ms.png",
    "mt.png",
    "mu.png",
    "mv.png",
    "mw.png",
    "mx.png",
    "my.png",
    "mz.png",
    "na.png",
    "nc.png",
    "ne.png",
    "nf.png",
    "ng.png",
    "ni.png",
    "nl.png",
    "no.png",
    "np.png",
    "nr.png",
    "nu.png",
    "nz.png",
    "om.png",
    "pa.png",
    "pe.png",
    "pf.png",
    "pg.png",
    "ph.png",
    "pk.png",
    "pl.png",
    "pm.png",
    "pn.png",
    "pr.png",
    "ps.png",
    "pt.png",
    "pw.png",
    "py.png",
    "qa.png",
    "re.png",
    "ro.png",
    "rs.png",
    "ru.png",
    "rw.png",
    "sa.png",
    "sb.png",
    "sc.png",
    "sd.png",
    "se.png",
    "sg.png",
    "sh.png",
    "si.png",
    "sj.png",
    "sk.png",
    "sl.png",
    "sm.png",
    "sn.png",
    "so.png",
    "sr.png",
    "ss.png",
    "st.png",
    "sv.png",
    "sx.png",
    "sy.png",
    "sz.png",
    "tc.png",
    "td.png",
    "tf.png",
    "tg.png",
    "th.png",
    "tj.png",
    "tk.png",
    "tl.png",
    "tm.png",
    "tn.png",
    "to.png",
    "tr.png",
    "tt.png",
    "tv.png",
    "tw.png",
    "tz.png",
    "ua.png",
    "ug.png",
    "um.png",
    "us.png",
    "uy.png",
    "uz.png",
    "va.png",
    "vc.png",
    "ve.png",
    "vg.png",
    "vi.png",
    "vn.png",
    "vu.png",
    "wf.png",
    "ws.png",
    "xk.png",
    "ye.png",
    "yt.png",
    "za.png",
    "zm.png",
    "zw.png",
  ];
  static List<String> sourasCategory = ["TIWAL", "MIIN", "MATHANI", "MOFASAL"];
  static double categoryGrade(String cat) {
    switch (cat) {
      case ("TIWAL"):
        return 10;
      case ("MIIN"):
        return 7;
      case ("MATHANI"):
        return 5;
      case ("MOFASAL"):
        return 2;
      default:
        return 2;
    }
  }

  static List<DropdownMenuItem<double>> createSourasCategy() {
    return sourasCategory
        .map((e) => DropdownMenuItem(child: Text(e), value: categoryGrade(e)))
        .toList();
  }

  static List<DropdownMenuItem<dynamic>> createSourasDdwn(String cat) {
    switch (cat) {
      case ("TIWAL"):
        return tiwal
            .map((e) => DropdownMenuItem(
                child: Text(e["souraName"].toString()),
                value: e["souraNb"].toDouble()))
            .toList();

      case ("MIIN"):
        return miin
            .map((e) => DropdownMenuItem(
                child: Text(e["souraName"]), value: e["souraNb"]))
            .toList();

      case ("MATHANI"):
        return mathani
            .map((e) => DropdownMenuItem(
                child: Text(e["souraName"]), value: e["souraNb"]))
            .toList();

      case ("MOFASAL"):
        return mofasal
            .map((e) => DropdownMenuItem(
                child: Text(e["souraName"]), value: e["souraNb"]))
            .toList();

      default:
        return mofasal
            .map((e) => DropdownMenuItem(
                child: Text(e["souraName"]), value: e["souraNb"]))
            .toList();
    }
  }
/*   static List<Ayah> getAyahGrid(){
    
} */
}
