// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRg4MjkIlI_SHCT3MG7aeymnZL1C7laU',
    appId: '1:482856935751:web:adab3072e27d9ef24c2c62',
    messagingSenderId: '482856935751',
    projectId: 'lami1a-1',
    authDomain: 'lami1a-1.firebaseapp.com',
    databaseURL:
        'https://lami1a-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lami1a-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5qiSXqBKE6rbtzbY790bfVdSz5B01vA4',
    appId: '1:482856935751:android:1d88c0eade9b79ea4c2c62',
    messagingSenderId: '482856935751',
    projectId: 'lami1a-1',
    databaseURL:
        'https://lami1a-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lami1a-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMw0ttp_G7NSXextkKSHvtUV_-0f_iPSA',
    appId: '1:482856935751:ios:a40253ee8d71841f4c2c62',
    messagingSenderId: '482856935751',
    projectId: 'lami1a-1',
    databaseURL:
        'https://lami1a-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lami1a-1.appspot.com',
    iosClientId:
        '482856935751-mlltf8qcq5t46rrp00703fc74rl3bpjr.apps.googleusercontent.com',
    iosBundleId: 'com.liismaiil.asasiyat',
  );
}
